### ISSUE TITLE
jwst_backgrounds not working after upgrade 

### ISSUE THREAD

**Issue by janerigby** [spacetelescope/jwst_backgrounds#21]
Hi All!  I have a new computer and just installed jwst_backgrounds from pip.  I'm getting a weird error related to the URL libraries.  Error messages below.  Please advise.

(base) gs66-kameny:jrr jrrigby1$ jwst_backgrounds --day 120  120.00 -33.000 2.0 
Traceback (most recent call last):
  File "/Users/jrrigby1/miniforge3/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/jrrigby1/miniforge3/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/jrrigby1/miniforge3/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/jrrigby1/miniforge3/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/jrrigby1/miniforge3/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/jrrigby1/miniforge3/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/jrrigby1/miniforge3/lib/python3.9/http/client.py", line 1447, in connect
    super().connect()
  File "/Users/jrrigby1/miniforge3/lib/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "/Users/jrrigby1/miniforge3/lib/python3.9/socket.py", line 823, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Users/jrrigby1/miniforge3/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jrrigby1/miniforge3/lib/python3.9/site-packages/jwst_backgrounds/jbt.py", line 127, in read_bkg_data
    version_file = urllib.request.urlopen(self.cache_url + 'VERSION')
  File "/Users/jrrigby1/miniforge3/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/jrrigby1/miniforge3/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Users/jrrigby1/miniforge3/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/jrrigby1/miniforge3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Users/jrrigby1/miniforge3/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/jrrigby1/miniforge3/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jrrigby1/miniforge3/bin/jwst_backgrounds", line 8, in <module>
    sys.exit(main())
  File "/Users/jrrigby1/miniforge3/lib/python3.9/site-packages/jwst_backgrounds/cli.py", line 30, in main
    jbt.get_background(float(opt['<ra>']),float(opt['<dec>']),float(opt['<wavelength>']), \
  File "/Users/jrrigby1/miniforge3/lib/python3.9/site-packages/jwst_backgrounds/jbt.py", line 361, in get_background
    bkg = background(ra,dec,wavelength, thresh=thresh)
  File "/Users/jrrigby1/miniforge3/lib/python3.9/site-packages/jwst_backgrounds/jbt.py", line 69, in __init__
    self.bkg_data = self.read_bkg_data(self.cache_file)
  File "/Users/jrrigby1/miniforge3/lib/python3.9/site-packages/jwst_backgrounds/jbt.py", line 132, in read_bkg_data
    version_file = urllib.urlopen(self.cache_url + 'VERSION')
AttributeError: module 'urllib' has no attribute 'urlopen'

**Comment by janerigby** [comment]
It's possible this is a Python 2x --> python 3 version?

**Comment by janerigby** [comment]
Disregard, this was a weird interaction on my shell
